version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-j2bf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quiz
      MYSQL_USER: quiz
      MYSQL_PASSWORD: quiz
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  test-api:
    image: test-api:dev
    ports:
      - "5000:5000"
    # command: 'npm run migrate'
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: quiz
      DB_PASSWORD: quiz
      DB_NAME: quiz
volumes:
  dbdata:
