version: "3"

services:
  test-api:
    image: test-api:dev
    ports:
      - "5000:5000"
    # command: 'npm run migrate'
    environment:
      NODE_ENV: development
      PORT: 5000
volumes:
  dbdata:
